import React, { useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Bot, CheckCircle2, Database, Menu, MessageSquare, ShieldCheck, Sparkles, Workflow, X } from "lucide-react";

export default function App() {
  const [menuOpen,setMenuOpen]=useState(false);
  const services=[
    [Bot,"AI Strategy & Consulting","Identify high-value AI opportunities and turn them into a practical implementation roadmap."],
    [Workflow,"Workflow Automation","Automate repetitive business processes using AI, Power Automate and intelligent approval workflows."],
    [MessageSquare,"AI Agents & Copilots","Build internal AI assistants for IT support, HR, operations, customer service and knowledge access."],
    [Database,"Business Systems Integration","Connect AI solutions with CRM, ERP, SharePoint, Dataverse and other business applications."],
    [ShieldCheck,"AI Readiness & Governance","Prepare your organisation for secure, responsible and scalable AI adoption."],
    [Sparkles,"Training & Adoption","Help teams understand AI tools and confidently incorporate them into everyday work."]
  ];
  const steps=[["01","Discover","We understand your business, challenges and current processes."],["02","Design","We create a practical AI solution and implementation roadmap."],["03","Build","We configure, integrate and test the solution with your team."],["04","Scale","We measure results, train users and expand what works."]];
  return <main className="min-h-screen bg-slate-950 text-white selection:bg-cyan-300 selection:text-slate-950">
    <nav className="sticky top-0 z-50 border-b border-white/10 bg-slate-950/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 lg:px-8"><a href="#home" className="flex items-center gap-2 font-bold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-cyan-300 text-slate-950"><Sparkles size={18}/></span>Lindava Intelligence</a><div className="hidden gap-8 text-sm text-slate-300 md:flex">{["services","process","about","contact"].map(x=><a key={x} className="capitalize hover:text-white" href={`#${x}`}>{x}</a>)}</div><a className="hidden rounded-full bg-cyan-300 px-5 py-2.5 text-sm font-semibold text-slate-950 md:block" href="#contact">Book a consultation</a><button className="md:hidden" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></div>{menuOpen&&<div className="space-y-4 border-t border-white/10 px-6 py-5 md:hidden">{["services","process","about","contact"].map(x=><a key={x} className="block capitalize" onClick={()=>setMenuOpen(false)} href={`#${x}`}>{x}</a>)}</div>}</nav>
    <section id="home" className="relative overflow-hidden"><div className="absolute left-1/2 top-20 h-[520px] w-[520px] -translate-x-1/2 rounded-full bg-cyan-400/15 blur-[130px]"/><div className="relative mx-auto grid max-w-7xl gap-14 px-6 py-24 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:py-32"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-cyan-300/25 bg-cyan-300/10 px-4 py-2 text-xs font-semibold uppercase tracking-[.18em] text-cyan-200"><Sparkles size={14}/> Practical AI for real business</div><h1 className="text-5xl font-black leading-[.98] tracking-[-.05em] sm:text-6xl lg:text-7xl">Turn AI into measurable <span className="text-cyan-300">business value.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">We help businesses automate processes, deploy AI assistants and integrate intelligent solutions with the systems their teams already use.</p><div className="mt-9 flex flex-wrap gap-3"><a className="rounded-full bg-cyan-300 px-6 py-3 font-semibold text-slate-950" href="#contact">Start your AI journey</a><a className="rounded-full border border-white/20 bg-white/5 px-6 py-3 font-semibold" href="#services">Explore services</a></div><div className="mt-9 flex flex-wrap gap-5 text-sm text-slate-400">{["Business-first approach","Secure by design","Built for adoption"].map(x=><span className="flex items-center gap-2" key={x}><CheckCircle2 size={16} className="text-cyan-300"/>{x}</span>)}</div></motion.div><div className="rounded-[2rem] border border-white/10 bg-gradient-to-br from-white/10 to-white/[.03] p-6 shadow-2xl"><p className="text-xs uppercase tracking-[.2em] text-slate-400">AI Opportunity Map</p><p className="mt-1 text-xl font-semibold">Your business, intelligently connected</p><div className="grid grid-cols-2 gap-3 py-8">{[[Bot,"AI Agent"],[Workflow,"Automation"],[Database,"Business Data"],[ShieldCheck,"Governance"]].map(([I,l],i)=><div key={l} className={`rounded-2xl border border-white/10 p-5 ${i===0?'bg-cyan-300 text-slate-950':'bg-slate-900/70'}`}><I className="mb-8"/><p className="font-semibold">{l}</p><p className={`mt-1 text-xs ${i===0?'text-slate-700':'text-slate-400'}`}>Connected solution</p></div>)}</div><div className="rounded-2xl border border-white/10 bg-slate-900/70 p-5"><div className="flex justify-between text-sm"><span className="text-slate-400">Transformation roadmap</span><span className="text-cyan-300">Ready</span></div><div className="mt-4 h-2 rounded-full bg-white/10"><div className="h-full w-[82%] rounded-full bg-gradient-to-r from-cyan-300 to-blue-400"/></div></div></div></div></section>
    <section id="services" className="bg-slate-900/45 py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[.22em] text-cyan-300">What we do</p><h2 className="mt-3 max-w-3xl text-4xl font-bold tracking-tight sm:text-5xl">AI services designed around your business.</h2><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map(([I,t,d])=><div key={t} className="rounded-[1.6rem] border border-white/10 bg-white/[.04] p-7"><div className="mb-7 grid h-12 w-12 place-items-center rounded-2xl bg-cyan-300/10 text-cyan-300"><I/></div><h3 className="text-xl font-semibold">{t}</h3><p className="mt-3 leading-7 text-slate-400">{d}</p></div>)}</div></div></section>
    <section id="process" className="py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[.22em] text-cyan-300">How it works</p><h2 className="mt-3 text-4xl font-bold sm:text-5xl">From idea to impact.</h2><div className="mt-14 grid gap-8 md:grid-cols-4">{steps.map(([n,t,d])=><div key={n} className="border-t border-white/15 pt-5"><span className="font-mono text-sm text-cyan-300">{n}</span><h3 className="mt-6 text-xl font-semibold">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{d}</p></div>)}</div></div></section>
    <section id="about" className="pb-24"><div className="mx-auto max-w-7xl px-6"><div className="grid gap-10 rounded-[2rem] border border-white/10 bg-gradient-to-br from-cyan-300/10 to-blue-500/5 p-8 md:grid-cols-2 md:p-12"><div><p className="text-sm font-bold uppercase tracking-[.22em] text-cyan-300">Why Lindava Intelligence</p><h2 className="mt-4 text-3xl font-bold">Technology should simplify work, not add complexity.</h2></div><div className="space-y-5 text-slate-300"><p>We combine business process thinking with modern AI and automation to solve practical operational challenges.</p><p>Our approach focuses on clear use cases, integration with existing systems, responsible deployment and user adoption.</p></div></div></div></section>
    <section id="contact" className="pb-24"><div className="mx-auto max-w-5xl px-6 text-center"><div className="rounded-[2rem] bg-cyan-300 px-7 py-14 text-slate-950"><p className="text-sm font-bold uppercase tracking-[.2em]">Ready to get started?</p><h2 className="mx-auto mt-4 max-w-3xl text-4xl font-black md:text-5xl">Let's find where AI can make the biggest difference in your business.</h2><p className="mx-auto mt-5 max-w-xl text-slate-700">Book a discovery session and we'll identify practical opportunities for automation, AI agents and smarter processes.</p><a className="mt-8 inline-flex items-center rounded-full bg-slate-950 px-7 py-3 font-semibold text-white" href="mailto:lindav@steiner.co.za?subject=AI%20Consultation%20Request%20-%20Lindava%20Intelligence">Book a free consultation <ArrowRight className="ml-2"/></a><p className="mt-5 text-sm font-semibold text-slate-700">0826249182</p></div></div></section>
    <footer className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-6 py-8 text-sm text-slate-500 md:flex-row md:justify-between"><span>© 2026 Lindava Intelligence. All rights reserved.</span><span>AI Consulting • Automation • Intelligent Business Solutions</span></div></footer>
  </main>;
}
